project:
  type: website
  output-dir: docs
  
website:
  title: "Navigation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobby.qmd
        text: Hobby
      - href: movie.qmd
        text: Movie
      - href: project.qmd
        text: Project
        
format:
  html:
    theme: yeti
    css: style.css
    toc: true