project:
  type: website
  output-dir: docs
  
website:
  title: "temp_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobby.qmd
        text: Hobby

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true